<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15650" started-at="2016-08-30T21:08:14Z" finished-at="2016-08-30T21:08:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15650" started-at="2016-08-30T21:08:14Z" finished-at="2016-08-30T21:08:30Z">
      <class name="ChallengeExcercise.UserRegistration">
        <test-method status="PASS" signature="setUp()[pri:0, instance:ChallengeExcercise.UserRegistration@4a6487f7]" name="setUp" is-config="true" duration-ms="4485" started-at="2016-08-30T17:08:10Z" finished-at="2016-08-30T17:08:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testUserLoginNG()[pri:0, instance:ChallengeExcercise.UserRegistration@4a6487f7]" name="testUserLoginNG" duration-ms="15632" started-at="2016-08-30T17:08:14Z" finished-at="2016-08-30T17:08:30Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at ChallengeExcercise.UserRegistration.testUserLoginNG(UserRegistration.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserLoginNG -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:ChallengeExcercise.UserRegistration@4a6487f7]" name="tearDown" is-config="true" duration-ms="831" started-at="2016-08-30T17:08:30Z" finished-at="2016-08-30T17:08:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ChallengeExcercise.UserRegistration -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
